/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VarButton: typeof import('@varlet/ui')['_ButtonComponent']
    VarCard: typeof import('@varlet/ui')['_CardComponent']
    VarCounter: typeof import('@varlet/ui')['_CounterComponent']
    VarDivider: typeof import('@varlet/ui')['_DividerComponent']
    VarIcon: typeof import('@varlet/ui')['_IconComponent']
    VarImage: typeof import('@varlet/ui')['_ImageComponent']
    VarUploader: typeof import('@varlet/ui')['_UploaderComponent']
  }
  export interface GlobalDirectives {
    vRipple: typeof import('@varlet/ui')['_RippleComponent']
  }
}
